"""
LLM generation module for the RAG knowledge system.

Combines a user's question with retrieved context and generates
a grounded response using an LLM.
"""

from typing import Dict, List

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()


class LLMGenerator:
    """Generate grounded responses from retrieved context."""

    def __init__(
        self,
        model: str = "gpt-4.1-mini",
    ):
        self.client = OpenAI()
        self.model = model

    def generate(
        self,
        query: str,
        retrieved_context: List[Dict],
    ) -> str:
        """
        Generate an answer using retrieved knowledge.

        Parameters
        ----------
        query : str
            User's question.

        retrieved_context : List[Dict]
            Relevant chunks retrieved from the knowledge base.

        Returns
        -------
        str
            Grounded response generated by the LLM.
        """

        if not query.strip():
            raise ValueError("Query cannot be empty.")

        if not retrieved_context:
            return (
                "I could not find sufficient information in the "
                "available knowledge base to answer this question."
            )

        context_blocks = []

        for item in retrieved_context:
            source = item.get("source", "Unknown source")
            content = item.get("content", "")

            context_blocks.append(
                f"[Source: {source}]\n{content}"
            )

        context = "\n\n".join(context_blocks)

        system_prompt = """
You are a knowledge assistant operating within a Retrieval-Augmented
Generation (RAG) system.

Answer the user's question using only the retrieved context provided.

Rules:
1. Do not invent facts that are not supported by the context.
2. If the context does not contain enough information, say so clearly.
3. Distinguish between facts in the retrieved context and uncertainty.
4. Keep the answer concise, clear, and useful.
5. Where appropriate, identify the source of the information.
"""

        user_prompt = f"""
Retrieved Context:

{context}

User Question:

{query}

Provide a grounded answer based on the retrieved context.
"""

        response = self.client.responses.create(
            model=self.model,
            instructions=system_prompt,
            input=user_prompt,
        )

        return response.output_text
